name: End-to-end tests 🧪
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and open all Cypress tests
      - name: cypress open --config-file=cypress.config.js
        uses: cypress-io/github-action@v2